
#ifndef RESOURCESID_H_
#define RESOURCESID_H_
//resource type
#include "Manager/ResourcesNameRole.h"

enum idImages {
//	//common
//	IMAGE_BACKGROUND = TYPE_IMAGE + SCENE_COMMON + STAGE_NONE + 1,
//	IMAGE_MAIN_BACKGROUND,
//	IMAGE_BACKGROUND_TABLE,
//	//mainmenu
//	IMAGE_VERTICALLY_START_BUTTON = TYPE_IMAGE + SCENE_MAINMENU + STAGE_NONE + 1,/////////////
//	IMAGE_VERTICALLY_TUTORIAL_BUTTON,/////////////
//	IMAGE_TITLE,
//	//tutorial
//	IMAGE_TUTORIAL = TYPE_IMAGE + SCENE_TUTORIAL + STAGE_NONE + 1,
//	IMAGE_BACK_BOUTTON,
//	//gameplay - gameplay
//	IMAGE_HAND = TYPE_IMAGE + SCENE_GAMEPLAY + STAGE_GAMEPLAY + 1,
//	IMAGE_BLOCK,
//	IMAGE_ACCURACY,
//	IMAGE_SCORE,
//	IMAGE_SCORENUMBER,
//	IMAGE_TIMEBAR,
//	//gameplay - gameover
//	IMAGE_GAMEOVER = TYPE_IMAGE + SCENE_GAMEPLAY + STAGE_GAMEOVER + 1,
//	//gameresult
//	IMAGE_HORIZONTAL_BUTTON = TYPE_IMAGE + SCENE_GAMERESULT + STAGE_NONE + 1,
//	IMAGE_RESULT_WINDOW,
//
//	LABLE_NAME,
//	LABLE_BLOCKS,
//	LABLE_SCORE,
//
//	LABLE_FIRST_NAME,
//	LABLE_SECOND_NAME,
//	LABLE_THIRD_NAME,
//	LABLE_FOURTH_NAME,
//	LABLE_FIFTH_NAME,
//
//	LABLE_FIRST_BLOCKS,
//	LABLE_SECOND_BLOCKS,
//	LABLE_THIRD_BLOCKS,
//	LABLE_FOURTH_BLOCKS,
//	LABLE_FIFTH_BLOCKS,
//
//	LABLE_FIRST_SCORE,
//	LABLE_SECOND_SCORE,
//	LABLE_THIRD_SCORE,
//	LABLE_FOURTH_SCORE,
//	LABLE_FIFTH_SCORE,

};
enum idSounds {
	//common
	SOUND_CLICK = TYPE_SOUND + SCENE_COMMON + STAGE_NONE + 1,
	SOUND_INTRO,
	//mainmenu
	SOUND_MENUAUDIO = TYPE_SOUND + SCENE_MAINMENU + STAGE_NONE + 1,

	SOUND_STOREAUDIO = TYPE_SOUND + SCENE_STORE + STAGE_NONE + 1,

	//gameplay - none
	SOUND_PALYAUDIO_1 = TYPE_SOUND + SCENE_GAMEPLAY + STAGE_1 + 1,
	//gameplay - none
	SOUND_PALYAUDIO_2 = TYPE_SOUND + SCENE_GAMEPLAY + STAGE_2 + 1,
	//gameplay - none
	SOUND_PALYAUDIO_3 = TYPE_SOUND + SCENE_GAMEPLAY + STAGE_3 + 1,

	//gameplay - gameplay
	SOUND_ENEMYHIT = TYPE_SOUND + SCENE_GAMEPLAY + STAGE_COMMON + 1,
	SOUND_READYAUDIO,
	SOUND_COMEBACK,
	SOUND_SHOT,
	SOUND_CARCOME,
	SOUND_SIREN,

	//gameresult
	SOUND_RESULT = TYPE_SOUND + SCENE_GAMERESULT + STAGE_NONE + 1,
	SOUND_KILLALL
};

#endif /* RESOURCESID_H_ */

